website improvement
emberfest/emberfest.github.io pull request #214
Opened 2020-09-14 06:17 UTC by JaninaBodi

Improved the website to make it look more like Mar's design, some things are still not 100% in line so I'll continue working on that.

2020-09-28 11:46 UTC, marcoow reviewed
Looks good – just one thing I recognized: the chameleon next to the form is a bit distorted on medium size viewports:

<img width="808" alt="Bildschirmfoto 2020-09-28 um 13 45 22" src="https://user-images.githubusercontent.com/1510/94428450-fad34400-0190-11eb-8b45-50758e4b2f7c.png">

2020-09-30 06:10 UTC, marcoow reviewed
👍 some minor things left to fix

2020-09-30 06:10 UTC, marcoow commented on css/app.scss
> +        display: block;
this seems duplicated

2020-09-30 06:10 UTC, marcoow commented on css/app.scss
> +}
this shouldn't be needed?

2020-09-30 06:10 UTC, marcoow commented on css/app.scss
> +    height: 1146px;
we shouldn't be setting `height` on `div`s but let the content of the `div` determine its `height`

2020-09-30 06:10 UTC, marcoow commented on css/app.scss
> +    height: 727px;
see below – we shouldn't be setting `height` on `div`s

2020-10-01 14:53 UTC, marcoow requested changes
the chameleon is too big now on tablets:

![deploy-preview-214--silly-leavitt-2e0668 netlify app_](https://user-images.githubusercontent.com/1510/94825496-8c97b700-0406-11eb-993c-bb9d7f685ed0.png)

2020-10-05 10:57 UTC, JaninaBodi commented
@marcoow Oh, that's weird, I didn't change anything and when I look at it, it has the correct size, so I don't really know what to change?

2020-10-05 11:21 UTC, marcoow commented
@JaninaBodi change the width of the window a bit – it's off for widths between mobile and desktop only

2020-10-05 12:56 UTC, JaninaBodi commented
@marcoow I think I found the problem, is it the right size now? I mean it is when I zoom in or out on the window on my laptop

2020-10-05 12:58 UTC, marcoow approved these changes

2020-10-05 12:58 UTC, merged