Cleaning up codes
emberfest/emberfest.github.io pull request #239
Opened 2021-06-21 09:18 UTC by mandurisaimounika

2021-06-23 08:30 UTC, mandurisaimounika commented
@marcoow the codes has been deleted and re-coded again with optimizations.
The "Sign Up form " and "Footer" codes are pending
![Screenshot 2021-06-23 at 10 30 26](https://user-images.githubusercontent.com/25219517/123063860-0eed5e80-d40e-11eb-90ca-54be9183e4ef.png)

2021-06-23 14:43 UTC, mandurisaimounika commented
@marcoow all the html and css changes are done. Testing the build.
![Screenshot 2021-06-23 at 16 43 06](https://user-images.githubusercontent.com/25219517/123117597-2cd4b680-d442-11eb-8f53-5925d2edc0bc.png)
![Screenshot 2021-06-23 at 16 43 35](https://user-images.githubusercontent.com/25219517/123117612-3100d400-d442-11eb-9e1d-19b1cddab3fb.png)

2021-06-24 13:26 UTC, marcoow reviewed
The code looks much better now! I think there are some smaller visual issues still:

* I guess the headers should have some more space around them? <img width="986" alt="Bildschirmfoto 2021-06-24 um 15 21 47" src="https://user-images.githubusercontent.com/1510/123270528-45a3a180-d500-11eb-8252-d41c288c757d.png">
* Some of the sponsor logos seem to be outside the viewport for some screen sizes: <img width="667" alt="Bildschirmfoto 2021-06-24 um 15 20 04" src="https://user-images.githubusercontent.com/1510/123270592-57854480-d500-11eb-953f-6f2ef5cf3e0b.png">

I think in general, we shouldn't be using pixel values in CSS but units like `em` and `rem`. I'm not the most knowledgeable person on the team but I'm sure there'll be someone who can explain and help with this in our Slack in #tech or #ember.

2021-06-24 13:26 UTC, marcoow commented on images/2021 _ motif _ decorative element.svg
> +<?xml version="1.0" encoding="UTF-8"?>
we should make sure there are no spaces in file names.

2021-06-24 16:10 UTC, mandurisaimounika commented on images/2021 _ motif _ decorative element.svg
> +<?xml version="1.0" encoding="UTF-8"?>
- Headers spacing has been resolved
<img width="1121" alt="Screenshot 2021-06-24 at 17 58 22" src="https://user-images.githubusercontent.com/25219517/123296028-91614580-d516-11eb-83e6-d91c0f498431.png">

- The sponsors logo looks fine for me in all the screen viewports. Please mention the screen size in which it is breaking
<img width="297" alt="Screenshot 2021-06-24 at 17 58 03" src="https://user-images.githubusercontent.com/25219517/123296172-b786e580-d516-11eb-966d-f5c8ba003223.png">

- I have used "interpolate" in css which will not accept the "em" and "rem". This is the reason I am using the pixel values.
- The white spaces in the file name is also fixed
<img width="908" alt="Screenshot 2021-06-24 at 18 07 49" src="https://user-images.githubusercontent.com/25219517/123297011-72af7e80-d517-11eb-9d87-a3a4593bf93f.png">

2021-06-24 17:50 UTC, marcoow commented on images/2021 _ motif _ decorative element.svg
> +<?xml version="1.0" encoding="UTF-8"?>
I'm not sure what `interpolate(…` is tbh and can't find documentation on it – could you link to some docs?

2021-06-24 18:39 UTC, mandurisaimounika commented on images/2021 _ motif _ decorative element.svg
> +<?xml version="1.0" encoding="UTF-8"?>
https://www.geeksforgeeks.org/sass-interpolation/ and https://sass-lang.com/documentation/interpolation 
These are the documentations related to the "Interpolation" in Sass.

2021-06-25 06:21 UTC, marcoow commented on images/2021 _ motif _ decorative element.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Ah, I get it now – there's a mixin called `interpolate`! Can you move that out of `_reset.css`? "reset" in CSS usually refers to resetting all default browser styles to a common baseline and having mixins defined in a file called `_reset.css` is confusing.

I'm also not sure what that mixin does tbh. I think it'd be better to use relative units.

2021-06-25 07:12 UTC, mandurisaimounika commented on images/2021 _ motif _ decorative element.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Yes, it is a mixin. I moved out the mixin code from "_reset.css".

2021-06-29 15:52 UTC, marcoow commented on css/_mixins.scss
> +@mixin interpolate($property, $min-screen, $min-value, $max-screen, $max-value, $easing : "linear", $bending-points : 2) {
As discussed, we should be removing this mixin (and the other related ones). It's extremely complex code that also seems to be made for animations which we don't have anyway.

2021-06-29 15:52 UTC, marcoow commented on css/_mixins.scss
> +  }
I think these are good to have 👍

2021-06-29 15:52 UTC, marcoow commented on css/_reset.scss
> +}
Only this part is what's commonly referred to as _"reset.css"_ – I think everything else should be removed from this file as it's a bit irritating to have it in here. The classes below could maybe go into `common.scss` and the mixins at the top should likely just be deleted – see comment above.

2021-06-29 15:57 UTC, marhigh commented
There are a lot of elements that are not 1:1 with the design, but I would be unable to do a proper design review until Friday which is too late for @mandurisaimounika 's timeline. Therefore, to be practical, my only request would be to fix the primary CTA of the hero in a small viewport as it's currently unreadable: 

<img width="486" alt="Screen Shot 2021-06-29 at 17 53 52" src="https://user-images.githubusercontent.com/8226112/123830306-766e4700-d903-11eb-89fc-c714a268f6f0.png">

2021-06-29 15:57 UTC, marhigh approved these changes

2021-06-30 08:39 UTC, mandurisaimounika commented on css/_reset.scss
> +}
@marcoow I removed all the codes related to the "interpolate" mixin.

As per your request, changed the pixel values to rem.

2021-06-30 08:40 UTC, mandurisaimounika commented
> There are a lot of elements that are not 1:1 with the design, but I would be unable to do a proper design review until Friday which is too late for @mandurisaimounika 's timeline. Therefore, to be practical, my only request would be to fix the primary CTA of the hero in a small viewport as it's currently unreadable:
> 
> <img alt="Screen Shot 2021-06-29 at 17 53 52" width="486" src="https://user-images.githubusercontent.com/8226112/123830306-766e4700-d903-11eb-89fc-c714a268f6f0.png">

The primary CTA has been fixed.
![Uploading Screenshot 2021-06-30 at 10.40.29.png…]()

2021-06-30 08:42 UTC, mandurisaimounika commented
> There are a lot of elements that are not 1:1 with the design, but I would be unable to do a proper design review until Friday which is too late for @mandurisaimounika 's timeline. Therefore, to be practical, my only request would be to fix the primary CTA of the hero in a small viewport as it's currently unreadable:
> 
> <img alt="Screen Shot 2021-06-29 at 17 53 52" width="486" src="https://user-images.githubusercontent.com/8226112/123830306-766e4700-d903-11eb-89fc-c714a268f6f0.png">

The primary CTA has been fixed.
<img width="408" alt="Screenshot 2021-06-30 at 10 40 29" src="https://user-images.githubusercontent.com/25219517/123930319-ecb88b00-d98f-11eb-9cf5-e568d7c403b6.png">

2021-06-30 10:05 UTC, marcoow reviewed
Please check the visual appearance for all viewport sizes again. Some sponsor logos are outside of the viewport for some sizes, the ticket button changes shape 1 second after loading the page and the venue image should have the same height as the text and map next to it. Unfortunately I don't have a lot of time now to check things but it'd be good if you reviewed everything carefully again and/or asked someone from the team to do it.

2021-06-30 10:05 UTC, marcoow commented on css/_reset.scss
> +}
These should also go in the general CSS file since they are not part of reset.

2021-06-30 10:05 UTC, marcoow commented on css/_variables.scss
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap');
I think this should go into the general CSS files since it't not a variable.

2021-06-30 10:23 UTC, mandurisaimounika commented on css/_reset.scss
> +}
Can you please mention the viewport sizes for which the sponsor logos are breaking?

2021-06-30 15:23 UTC, mandurisaimounika commented on css/_reset.scss
> +}
I fixed few issues I found while testing.

2021-08-02 08:52 UTC, marcoow requested changes
* [x] the header is broken on the content pages:

<img width="1281" alt="Bildschirmfoto 2021-08-02 um 10 43 36" src="https://user-images.githubusercontent.com/1510/127832837-56ace3e5-9257-480e-844c-5a27e0f36d9c.png">

* [x] the list on the privacy page is wrong for some screen widths:

<img width="686" alt="Bildschirmfoto 2021-08-02 um 10 43 53" src="https://user-images.githubusercontent.com/1510/127832982-dce737f9-234d-40bd-b5df-4885a2e85b38.png">

* [x] the map to the conference venue show be as wide a the image on smaller screens:

<img width="814" alt="Bildschirmfoto 2021-08-02 um 10 45 25" src="https://user-images.githubusercontent.com/1510/127833058-31913491-750b-420a-948b-b6595ab8d021.png">

* [ ] the logos don't fit the screen on narrow screens:

<img width="686" alt="Bildschirmfoto 2021-08-02 um 10 45 39" src="https://user-images.githubusercontent.com/1510/127833113-ebdd9622-f840-4b6e-abb2-57d48e9688d2.png">

2021-08-02 09:48 UTC, mandurisaimounika commented
> * [x]  the header is broken on the content pages:
> 
> <img alt="Bildschirmfoto 2021-08-02 um 10 43 36" width="1281" src="https://user-images.githubusercontent.com/1510/127832837-56ace3e5-9257-480e-844c-5a27e0f36d9c.png">
> 
> * [x]  the list on the privacy page is wrong for some screen widths:
> 
> <img alt="Bildschirmfoto 2021-08-02 um 10 43 53" width="686" src="https://user-images.githubusercontent.com/1510/127832982-dce737f9-234d-40bd-b5df-4885a2e85b38.png">
> 
> * [x]  the map to the conference venue show be as wide a the image on smaller screens:
> 
> <img alt="Bildschirmfoto 2021-08-02 um 10 45 25" width="814" src="https://user-images.githubusercontent.com/1510/127833058-31913491-750b-420a-948b-b6595ab8d021.png">
> 
> * [ ]  the logos don't fit the screen on narrow screens:
> 
> <img alt="Bildschirmfoto 2021-08-02 um 10 45 39" width="686" src="https://user-images.githubusercontent.com/1510/127833113-ebdd9622-f840-4b6e-abb2-57d48e9688d2.png">

@marcoow the changes requested above are fixed except for the sponsors logo. The sponsors logo is working fine for me in all the viewports in Chrome as well as in Safari.

2021-08-04 08:53 UTC, marcoow commented
Safari window made as narrow as possible with 2 tabs open:

<img width="686" alt="Bildschirmfoto 2021-08-04 um 10 52 44" src="https://user-images.githubusercontent.com/1510/128152301-f4e6aeb1-2369-4391-ae8a-d22d9f8aa0f9.png">

2021-08-05 11:31 UTC, marcoow commented
hm, seems to be caused by dragging the window…

2021-08-05 11:31 UTC, marcoow approved these changes

2021-08-05 11:38 UTC, merged