Add venue and closing dinner sections
emberfest/emberfest.github.io pull request #294
Opened 2022-07-11 10:37 UTC by inesilva

2022-07-11 16:32 UTC, oscard0m commented on css/app.scss
> +      }
I still see some space differences here.

2022-07-11 17:30 UTC, oscard0m approved these changes

2022-07-12 06:15 UTC, marcoow requested changes
Nice :+1:

Can we split this into separate PRs for the venue and the closing diner though? We'll announce the venue before the closing diner so need to merge separately.

Also, as a general practice, I'd recommend separating the formatting changes into their own PR as well – removing trailing spaces etc. is great but adding it all to this makes this PR unnecessarily big.

2022-07-12 10:45 UTC, oscard0m approved these changes

2022-07-13 09:09 UTC, marcoow reviewed
I think there's a bit of vertical space missing above the croissants here?

<img width="842" alt="Bildschirmfoto 2022-07-13 um 11 09 00" src="https://user-images.githubusercontent.com/1510/178696318-2163bf5a-d4e1-4d52-8d47-712f8a62ecef.png">

2022-07-13 09:10 UTC, marcoow commented
@jkintscher can you share in a comment here the real content for the location?

2022-07-14 06:08 UTC, marcoow commented on css/app.scss
> +>>>>>>> 053309e (Add venue section)
👀 :)

2022-07-14 09:10 UTC, oscard0m approved these changes

2022-07-14 10:33 UTC, marcoow approved these changes

2022-07-19 13:11 UTC, jkintscher commented
> @jkintscher can you share in a comment here the real content for the location?

Sure thing! We just received the address today, but I went stalking their website and this should have all the info as well as some photos that you can hopefully use: https://themragency.com/en/location/the-pavillon-rive-gauche/

If you need more details and/or pics, just let me know!

2022-07-21 08:21 UTC, marcoow commented
@inesilva can you update this with the actual location data that Joschka linked above?

2022-07-21 15:44 UTC, marcoow approved these changes
Nice 👍 Please hold off merging now – we need to synchronize this with sending out an email etc.

2022-07-22 07:10 UTC, balinterdi approved these changes

2022-07-24 10:51 UTC, merged