Add Presenters Section
emberfest/emberfest.github.io pull request #315
Opened 2022-08-24 10:05 UTC by inesilva

It closes #314

2022-08-24 10:28 UTC, oscard0m requested changes

2022-08-24 10:28 UTC, oscard0m commented on index.html
> +  <section class="presenters">
> We should add that section below the sponsors' section with

originally posted in the issue: https://github.com/emberfest/emberfest.github.io/issues/314

2022-08-24 10:28 UTC, oscard0m commented on index.html
> +          <img src="/images/sponsors/simplabs.svg" class="photo logo" />
🎨 We are already saying `simplabs` in L115. What do you think of using just simplabs logo, without the text?

<img width="328" alt="image" src="https://user-images.githubusercontent.com/2574275/186396014-2ebca183-3752-40c6-9a15-fe7959ffa125.png">

2022-08-24 10:28 UTC, oscard0m commented on index.html
> +          <h4>Simplabs</h4>
```suggestion
          <h4>simplabs</h4>
```

2022-08-24 10:36 UTC, inesilva commented on index.html
> +          <img src="/images/sponsors/simplabs.svg" class="photo logo" />
I think it is a good idea

2022-08-24 10:46 UTC, inesilva commented on index.html
> +  <section class="presenters">
oh I didn't notice, thanks!

2022-08-24 12:22 UTC, jkintscher submitted a review, later dismissed
Please replace Joachim, who’s left EmberFest in 2015, with my pic/links 🙏😅

2022-08-24 13:09 UTC, inesilva commented
> Please replace Joachim, who’s left EmberFest in 2015, with my pic/links 🙏😅

sorry! thanks for letting me know 😅

2022-08-25 07:30 UTC, oscard0m commented on index.html
> +  <section class="presenters">
Any idea on how to differentiate the presenters' section from the sponsors' section? A change of background maybe?

(I personally preferred to put the section below the speakers as you suggested initially... but maybe there's a reason to not do so)

2022-08-25 07:32 UTC, oscard0m approved these changes
Changes look good.

I personally don't like how the presenters look after the sponsors. I prefer what you suggested before (after the speakers) but... is a requirement of the task. Let's see what other reviewers say.

2022-08-25 12:08 UTC, balinterdi commented
> I personally don't like how the presenters look after the sponsors. I prefer what you suggested before (after the speakers) but... is a requirement of the task. Let's see what other reviewers say.

I agree, I think there should be more visual differentiation. Why is it a requirement of the task (or, where is this written)?

> Any idea on how to differentiate the presenters' section from the sponsors' section? A change of background maybe?

I'm not a designer, but a separate section with a different background color could work, I think, yes.

Also, we do we want to say "presenters"? We've so far used the word "organizers", though not officially. At any rate, that's not a hill I'm doing to die on, it's just that organizers sounds more natural to me, that's all.

2022-08-25 12:14 UTC, oscard0m commented
> > I personally don't like how the presenters look after the sponsors. I prefer what you suggested before (after the speakers) but... is a requirement of the task. Let's see what other reviewers say.
> 
> I agree, I think there should be more visual differentiation. Why is it a requirement of the task (or, where is this written)?

https://github.com/emberfest/emberfest.github.io/issues/314#issue-1348178215

> > Any idea on how to differentiate the presenters' section from the sponsors' section? A change of background maybe?
> 
> I'm not a designer, but a separate section with a different background color could work, I think, yes.
> 
> Also, we do we want to say "presenters"? We've so far used the word "organizers", though not officially. At any rate, that's not a hill I'm doing to die on, it's just that organizers sounds more natural to me, that's all.

I like 'organizers' as well.

2022-08-25 12:18 UTC, balinterdi commented
Right, but Marco's comment doesn't say that it needs to be blended into the Sponsors section just above it:

> Overall, that section can be visually the same as the "Speakers" section.

I think he refers more to the layout which you guys have done just fine. Discerning it visually from the section above it is fine (and, I'd add, better).

2022-08-25 15:38 UTC, oscard0m commented
> Right, but Marco's comment doesn't say that it needs to be blended into the Sponsors section just above it:

@balinterdi I got confused by this sentence but I agree is not very clear.
> **Note**
> We should add that section below the sponsors section - _Marco_

---

@inesilva I would add it under 'speakers' section as @balinterdi suggests.

2022-08-26 15:47 UTC, inesilva commented
I agree with putting it back under the speakers.
Regarding the naming, I don't have a strong opinion; it is more about what word represents you best @balinterdi

2022-08-26 17:37 UTC, balinterdi approved these changes
Thank you, Inês, looks good!

2022-09-01 09:01 UTC, merged