emberfest 2023 stage1
emberfest/emberfest.github.io pull request #385
Opened 2023-05-08 21:37 UTC by oscard0m

- feat(2022): move 2022 to /2022
- refactor(blogpost): move blogpost layouts under /2017 folder
- chore(gitignore): ignore .vscode/ local config
- feat(2023): frontpage stage 1

2023-05-08 21:45 UTC, oscard0m commented on css/app.scss
> +  height: 100vh;
This depends on the answer to this comment: https://github.com/emberfest/emberfest.github.io/issues/384#issuecomment-1539093352

Also, when we go for **Step 2**, we will remove this and let the sections grow the content of the frontpage, but for **Step 1**, we want to enforce a `100vh`

2023-05-08 21:46 UTC, oscard0m commented
@marcoow can we include @davidhajba in `github.com/emberfest` so we can request PR reviews from him?

2023-05-09 09:52 UTC, marcoow commented
invited David ✅

2023-05-09 09:57 UTC, marcoow requested changes
The 2022 page doesn't work – see at https://deploy-preview-385--silly-leavitt-2e0668.netlify.app/2022/

Didn't check in detail but obvious problems on first impression are links don't work and font is missing

2023-05-09 15:36 UTC, oscard0m commented
> The 2022 page doesn't work – see at https://deploy-preview-385--silly-leavitt-2e0668.netlify.app/2022/
> 
> Didn't check in detail but obvious problems on first impression are links don't work and font is missing

@marcoow I applied the fix for the broken links, only the ones for the `schedule` were broken as far as I could find.

Issue with the fonts broken fixed ✅

2023-05-10 06:02 UTC, marcoow reviewed
* schedule links in 2022 still not working, other links might not work neither, didn't check entire site
* all of the existing sites now need a 2023 link in the footer as well

2023-05-10 07:52 UTC, davidhajba commented
hey @oscard0m thanks for the updates - GitHub invite accepted

* vertical alignment for the Button is good (I think the font is a bit tricky, same for me)

* the footer (in the Sketch version) should not remove space from the viewport height of the hero section, 
it should come underneath as an extra scrollable space. What do you think? 

* thank you for the hover idea, my concern with it - as the orange is a very dominant color on other objects on the page, and turning the button text color orange too kind of hides the button between the other elements instead highlighting it. If I can make a suggestion for hower action [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/v/38YOOD/p/BE993FE2-E578-440C-A931-8457C6430A8A/canvas?posX=-533&posY=81&zoom=1) is my idea

* the arrows look broken on my side, could you please check?
<img width="1453" alt="Screenshot 2023-05-10 at 09 50 14" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/7442c260-1be7-4ed9-9dce-14af9e72e311">

* extra '-' at the end of a row  -  if it's cannot be removed, sure it shouldn't be a problem

2023-05-10 08:09 UTC, davidhajba commented
@oscard0m 
could you pls change the 'glasses-small' asset to the 'glasses-small-2' I just uploaded 

although the resolution is correct it is not sharp enough, I doubled the resolution (the size is still tiny)

assets are [HERE](https://shared-assets.adobe.com/link/1a48c974-c6cc-4c69-5572-4f68c4ea2aaa)

2023-05-12 10:33 UTC, oscard0m commented
@davidhajba 

> * the footer (in the Sketch version) should not remove space from the viewport height of the hero section,
>   it should come underneath as an extra scrollable space. What do you think?

I applied a `100vh` for the hero section + the content filling a `100%`. I would like @marcoow's opinion on this change, he has pointed out the issue of having a fixed height of elements as a danger practice for different viewport sizes.

> * thank you for the hover idea, my concern with it - as the orange is a very dominant color on other objects on the page, and turning the button text color orange too kind of hides the button between the other elements instead highlighting it. If I can make a suggestion for hower action [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/v/38YOOD/p/BE993FE2-E578-440C-A931-8457C6430A8A/canvas?posX=-533&posY=81&zoom=1) is my idea

Applied the `:hover` style you proposed for the **Book Your Ticket** button. I kept the hover style for the footer links. Is that ok?

> * the arrows look broken on my side, could you please check?

I tried a new approach. It looks better but not perfect. Let me know if it's enough.

> * extra '-' at the end of a row  -  if it's cannot be removed, sure it shouldn't be a problem

I posted this in #frontend because I'm out of ideas. The fact of having different viewport sizes makes this element to fluid in different ways so it's hard to target when a link is in row1 or row2 and if it's the first element of the row or not.

2023-05-12 12:00 UTC, davidhajba commented
FRONTPAGE - looks almost perfect, only 2 little details

* the line attached to the arrowhead in the footer should be 1,5 px instead of 2, so it will be the same boldness with the head and will be perfectly aligned to the center vertically. The other line in the footer without arr arrowheads is currently 3px, pls change it to 1,5 px too
<img width="712" alt="Screenshot 2023-05-12 at 13 57 34" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/86619945-c450-4e0c-8d13-b2a544418b68">

* can the '21-22 SEP. 2023 / LOCATION TBA' be closer to the top as it is [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/a/oMbvAyD) 

CODE OF CONDUCT, CANCELLATION POLICY, IMPRINT
* the changes I suggested in the other ticked are not updated yet, could you please check?

2023-05-15 08:42 UTC, davidhajba commented
hey @inesilva 
on my side, I do not see these changes
maybe because of Safari or I'm not sure

<img width="2056" alt="Screenshot 2023-05-15 at 10 40 48" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/7c27a986-ac71-4bea-9ee4-b841dfdf40c9">

2023-05-15 09:49 UTC, inesilva commented
> Details

I know what the problem is.
You are probably accessing through the links in the description, and they are outdated. I'll update them, but if you access through here, it is always the representation of the latest changes:
<img width="1173" alt="image" src="https://github.com/emberfest/emberfest.github.io/assets/15367376/0c32e0b1-6cba-45dc-8afb-47c855e88eba">

2023-05-15 11:48 UTC, davidhajba commented
@inesilva - sure I can use the other link, thank you.

 Only a few comments from my side, 
 
  * if I scroll further on the top & the bottom of the home page an extra darker color appears -> would be good to keep this in the same color as the background // and if we want to make it perfect see the background SVG too without cropping it //
 
<img width="1415" alt="Screenshot 2023-05-15 at 13 25 02" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/1b925ddb-8c3c-4673-8e73-0733d2ac85b9">
 
<img width="1416" alt="Screenshot 2023-05-15 at 13 24 30" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/0f69bf65-e806-41c3-8ce1-87f72014f477">

* The H1 font is an italic on the sub-pages <- this should be Extra-Bold (not italic)

<img width="1099" alt="Screenshot 2023-05-15 at 13 30 58" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/2a9547c0-a3a3-410c-a8fb-3a4ddb832595">

* The SVG  background element on the home page is perfect scale. 
On the sub-pages should be exactly the same too. (currently, it's different)

* Currently in the footer the arrow lines are 2px and the arrow-head SVGs are 1,5px.
We can go with the 2px arrow lines, but please change the arrow-heads for 2px too, I saved the assets [HERE](https://shared-assets.adobe.com/link/77f70c01-0762-46ff-460a-2bdf26bcd46c) 

Could you please help with these?
Other than these tiny details everything looks very beautiful 👌

2023-05-15 16:06 UTC, marcoow commented on _includes/hero.html
> +      <a alt="get involved!" href="#">Get involved!</a>
I can do it when everything else is ready

2023-05-15 16:07 UTC, marcoow commented on _includes/hero.html
> +      <a alt="get involved!" href="#">Get involved!</a>
Please use a `<button>` element for this though

2023-05-16 00:09 UTC, oscard0m commented
@davidhajba, we are already applying a background colour for the document's body with grey. I see it correctly in Chrome. In Safari, it shows the wrong background. I don't know why. When refreshing Safari, the background color is displayed correctly. I suggest creating an individual bug for this.

2023-05-16 00:17 UTC, oscard0m commented on _includes/hero.html
> +      <a alt="get involved!" href="#">Get involved!</a>
Considering this should be a link to the bottom of the page (#anchor-link), should this be a `<a>`, right?

2023-05-19 07:08 UTC, marcoow requested changes
Looks great overall! There's a few things left to change still, e.g. Papercall, ti.to, etc.

Also, the layout doesn't seem to work correctly for all mobile viewports?

<img src="https://github.com/emberfest/emberfest.github.io/assets/1510/df9c3c15-9f9d-47c2-b999-9144875a47c7" height="1000px" alt="app_code-of-conduct"/>

<img src="https://github.com/emberfest/emberfest.github.io/assets/1510/466286af-1457-4319-9639-d77771ea3e92" height="1000px" alt="netlify app_(Galaxy Fold)"/>

2023-05-19 07:08 UTC, marcoow commented on _includes/about.html
> +      While we're getting ready for EmberFest 2023 in Madrid, check out the
```suggestion
      While we're getting ready for EmberFest 2023, check out the
```

We're not announcing the host city yet

2023-05-19 07:08 UTC, marcoow commented on _includes/past-speakers.html
> +	<button href="" alt="Submit a Talk">Submit a Talk</button>
this should link to https://www.papercall.io/emberfest-2023

2023-05-19 07:08 UTC, marcoow commented on 2022/index.html
> +        </li>
let's put us in the middle

2023-05-19 07:08 UTC, marcoow commented on 2022/index.html
> +      </form>
This form doesn't seem to work properly? Try filling in values and submitting – the fields in the Mailchimp form are empty.

2023-05-19 07:08 UTC, marcoow commented on _includes/sidepages_header.html
> +  </picture>
the logo should link back to the homepage

2023-05-19 09:06 UTC, oscard0m commented on 2022/index.html
> +        </li>
This is 2022. Do we change it for **2022 only**, **2023 only** or **both**?

2023-05-19 09:18 UTC, marcoow commented on 2022/index.html
> +        </li>
ah, sorry – meant for 2023

2023-05-19 11:40 UTC, oscard0m commented
@davidhajba, when you have time, could you look at the `:hover` state of the buttons/links? Especially on the front page. I think we should arrive at a consensus on that.

2023-05-19 11:41 UTC, inesilva commented
@davidhajba 
<img width="845" alt="image" src="https://github.com/emberfest/emberfest.github.io/assets/15367376/3c911525-c41e-43a4-84d6-923342539bb8">
which text do you mean here?

2023-05-19 11:44 UTC, oscard0m commented
> @davidhajba <img alt="image" width="845" src="https://user-images.githubusercontent.com/15367376/239522990-3c911525-c41e-43a4-84d6-923342539bb8.png"> which text do you mean here?

I think he means the placeholder text.

2023-05-19 16:00 UTC, marcoow commented on imprint/index.html
> +            +49 89 452 139 03‬ <br />
```suggestion
            +49 89 452 139 03<br />
```

2023-05-22 08:29 UTC, davidhajba commented
Thank you for your amazing work @oscard0m @inesilva 
Things start to look fantastic !!!! 🎉

few things 

 FRONTPAGE
 
* this should not be wider then 650px
<img width="896" alt="239499011-53882474-5fb0-41cd-8d9c-4b5136e7cab8" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/61d00467-df1c-48a8-9c04-574aa61f5e16">

* as this content became shorted than in Sketch center alignment would be better (here and on mobile too as @oscar suggested)
<img width="682" alt="Screenshot 2023-05-22 at 09 46 03" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/dae4b9ad-89e2-4b7a-a3b1-9fd7ea18452f">

* please center align the content vertically here 
<img width="387" alt="Screenshot 2023-05-22 at 09 55 44" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/731657d0-d71b-4819-a1fc-7be9ff17491c">

* the distance here should not be bigger than 200px 
<img width="1332" alt="Screenshot 2023-05-22 at 10 01 16" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/824498c3-c219-450b-bf50-0e41470d4161">

* [HERE](https://www.sketch.com/s/150ed20a-d7c3-46a1-8151-89fba683acae/v/yxvQGy/p/BE993FE2-E578-440C-A931-8457C6430A8A/canvas?posX=-968.6367104980156&posY=-217.20209659788986&zoom=0.6473674774169922) are the hover actions of the social media buttons

Currently on the website the twitter yellow button the outline of the bird is a but distorted, and both yellow and blue button it doesn't look centered. I know it's positioned center, but because the shape of the bird it's tricky, so I saved all social media buttons [HERE](https://shared-assets.adobe.com/link/d8e276af-ef77-4cce-5755-9196ee124d9a)  as SVGs I think this is the easiest way to solve this. pls add the shadow to the blue buttons

CODE OF CONDUCT, CANCELLATION POLICY, IMPRINT

* the size of the SVG background element is not the same as on the Front page, could you please make it same size and position? 

<img width="2056" alt="Screenshot 2023-05-22 at 10 26 35" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/3b67bbcc-3ee7-4c8c-bb2e-f99c9ae1509f">
<img width="2056" alt="Screenshot 2023-05-22 at 10 26 22" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/47324500-1491-4ad8-8d63-10fd32de71c8">

2023-05-22 13:53 UTC, marcoow approved these changes
🎉

2023-05-22 13:55 UTC, marcoow commented
Only need to replace the video with the actual one from 2022 and add the sponsor prospectus once that's done…

2023-05-22 14:01 UTC, oscard0m commented
> Only need to replace the video with the actual one from 2022 and add the sponsor prospectus once that's done…

Awesome! Just to be sure: Is that on @davidhajba's backlog? @marcoow

2023-05-22 14:57 UTC, oscard0m commented
> don't think there's anything to do for David there?

@marcoow, where can we get the video and the prospectus?

2023-05-22 15:13 UTC, marcoow commented
I'll upload here once ready

2023-05-24 06:33 UTC, marcoow commented
here's the sponsor prospectus: 
[emberfest-2023-sponsorship-prospectus.pdf](https://github.com/emberfest/emberfest.github.io/files/11551179/emberfest-2023-sponsorship-prospectus.pdf)

2023-05-25 07:27 UTC, marcoow commented
…and the video: https://youtu.be/hvg35gS1Xjo

2023-05-25 08:00 UTC, marcoow approved these changes

2023-05-25 08:01 UTC, merged