Add bull and announce location
emberfest/emberfest.github.io pull request #404
Opened 2023-06-07 14:19 UTC by inesilva

# Description
- It adds the bull to the page titles
- Announce location

## [🔗 Preview Link](https://deploy-preview-404--silly-leavitt-2e0668.netlify.app/)

2023-06-07 14:33 UTC, davidhajba commented
hey @inesilva 
On my 16 inch screen I see this:
<img width="2056" alt="Screenshot 2023-06-07 at 16 30 26" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/6e44c12e-5b4d-4ff0-9f18-ab737a5166fa">

would it be possible to make the 'logo+bull' responsive too, 
as the svg element in the background, 
so on all desktop screens see something like this ?

<img width="1514" alt="Screenshot 2023-06-07 at 16 31 09" src="https://github.com/emberfest/emberfest.github.io/assets/78347340/ebbd8b67-e728-4e0e-a3a4-093c3bc57a89">

2023-06-07 14:35 UTC, oscard0m requested changes
frontpage is missing the date and location TBA, at least in my screen on Desktop: 
![image](https://github.com/emberfest/emberfest.github.io/assets/2574275/c33d572b-6332-4cfc-a2c8-eb4c23badd05)

@davidhajba could you take a look on mobile? LOCATION TBA gets an extra so I think we should consider a way to better arrange this.

2023-06-07 14:43 UTC, oscard0m commented on _includes/hero.html
> +      <img src="/images/title-with-bull.svg" alt="EmberFest logo with a bull underneath wearing red glasses" />
Could you review the associated CSS? If `<div class="logos-container">` has one child, the `display: flex`, `gap`, etc do not apply anymore 🧹.

2023-06-07 15:20 UTC, marcoow requested changes
"LOCATION TBA" should be changed to "MADRID"

This doesn't work on mobile yet: 
![deploy-preview-404--silly-leavitt-2e0668 netlify app_](https://github.com/emberfest/emberfest.github.io/assets/1510/45d71246-d568-443a-83b4-cef57f7ee9f5)

2023-06-08 08:49 UTC, davidhajba commented
`could you take a look on mobile`
- sure, on mobile it looks good to me

`it is responsive. i added a max-width of 650px which is the size I see on sketch. should it be bigger than this?`
- in sketch I used a 14 inch screen, on larger screens the 'logo+bull head' should grow bigger together with the background svg element, would it be possible ?

2023-06-08 09:57 UTC, oscard0m commented
> * in sketch I used a 14 inch screen, on larger screens the 'logo+bull head' should grow bigger together with the background svg element, would it be possible ?

@davidhajba, just to be clear I'm understanding our request:
1. How the background resizes (in production for large screens) is OK **but** we need to adjust how the bull resizes for those screen sizes.
or
2. How the background resizes (in production for large screens) is NOT OK **and** we need to adjust how the bull resizes for those screen sizes.

2023-06-08 10:48 UTC, oscard0m commented
> * in sketch I used a 14 inch screen, on larger screens the 'logo+bull head' should grow bigger together with the background svg element, would it be possible ?

Can you take a look into it now? @davidhajba

2023-06-08 11:25 UTC, davidhajba commented
yep - looks perfect, thanks 👌

2023-06-08 11:26 UTC, davidhajba approved these changes

2023-06-08 11:30 UTC, oscard0m approved these changes

2023-06-08 12:19 UTC, marcoow approved these changes

2023-06-09 09:09 UTC, merged